version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: erp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: erp-adminer
    restart: always
    ports:
      - '8080:8080'

  backend:
    build: .
    container_name: erp-backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: erp

volumes:
  pgdata:
